### ISSUE TITLE
/scene does not work

### ISSUE THREAD

**Issue by HarlekinSimplex** [jshea2/OSC-for-OBS#7]
I have tried the following OSC calls from my TouchOSC surface to activate the scene 'CAMERA':
/scene CAMERA
/scene/CAMERA
/previewScene CAMERA
/previewScene/CAMERA
Further I tried to use different scene names with spaces in them to check if that works.
All of them did not work to activate my scene CAMERA at OBS.

Other calls like /go /back /toggleStudioMode do work as expected, so my setup in general is configured well.

Probably its an issue with the value range send alongside the OSC string.
However I haven't found any documentation regading those numbers and what is expected here to make those call work as expected.

**Comment by jshea2** [comment]
TouchOSC works a bit differently for triggering scenes because it sends an integer argument. If you join the discord I can send you a quick fix. I'm making a build with updates for TouchOSC soon. The current way to call scenes in TouchOSC is to just do /scene and use the value to the number that gets logged when you connect.

I'll look into the duplicate scene and fir to screen commands. Those are new. Make sure you're selected the source before you fittoscreen.

For the one button for the mute i can probably add a audiostatus command that can toggle between 1 and 0

**Comment by jshea2** [comment]
New v2.4 release should fix these issues!

**Comment by SD-phase** [comment]
> New v2.4 release should fix these issues!

Thank you sir!
